<?php
return [
    [
        'id' => 1,
        'status' => \uztelecom\entities\orders\Order::STATUS_ACTIVE,
        'from_lat' => 123.124,
        'from_lng' => 21.124,
        'from_address' => 'test address',
        'created_at' => time(),
        'created_by' => 1,
    ],
    [
        'id' => 2,
        'status' => \uztelecom\entities\orders\Order::STATUS_BUSY,
        'from_lat' => 123.124,
        'from_lng' => 21.124,
        'from_address' => 'test from address',
        'to_lat' => 324.124,
        'to_lng' => 52.124,
        'to_address' => 'test to address',
        'created_at' => time(),
        'created_by' => 1,
        'driver_id' => 2,
    ],
    [
        'id' => 3,
        'status' => \uztelecom\entities\orders\Order::STATUS_CANCELED,
        'from_lat' => 123.124,
        'from_lng' => 21.124,
        'from_address' => 'test from address',
        'to_lat' => 324.124,
        'to_lng' => 52.124,
        'to_address' => 'test to address',
        'created_at' => time(),
        'created_by' => 1,
        'driver_id' => 2,
        'completed_at' => time() + 30,
    ],
    [
        'id' => 4,
        'status' => \uztelecom\entities\orders\Order::STATUS_COMPLETED,
        'from_lat' => 123.124,
        'from_lng' => 21.124,
        'from_address' => 'test from address',
        'to_lat' => 324.124,
        'to_lng' => 52.124,
        'to_address' => 'test to address',
        'created_at' => time(),
        'created_by' => 1,
        'driver_id' => 2,
        'completed_at' => time() + 40,
    ],
];
